### ISSUE TITLE
Notebook Review

### ISSUE THREAD

**Issue by adelnehme** [datacamp/data-analysis-in-sql-live-training#1]
Hi @michlsemn habibi - I hope you're well! 

Here's my review of the notebook so far.

## General

:star: It's really cool to see how one column can really shed so much information on a dataset.

- [x] 🔧 **1.** I really like the questions being answered here. However, to make it flow a bit better and add more meat to the bones, I recommend adding some demographics data (Age, Gender, etc... - this could be in a separate table or in the same one) and changing up the outline slightly to:

> I) Setting Up PostgreSQL
> II) Exploring Dataset and Understanding Customer Base
> II - a) See the data
> II - b) Answer some key demographics questions (average age of the customer, gender parity, etc..) 
> **Q&A**
> III) Digging into User Activity 
> III - a) Active Users (daily + monthly)
> III - b) Registered Users 
> **Q&A**
> III - c) User Growth rate 
> **Q&A**
> IV) Churn and Retention
> **Q&A**

- [x] 🔧 **2.** Make sure when formatting headers that you always use the (header # - sub-header ## - sub-sub-header ###) when aligning the outline to the notebook and make sure to always **bold** headers, subheaders and sub-sub headers. 

- [x] 🔧 **3.** Instead of naming it "my app" or "your app" - why not come up with a fictional app similar to a popular app most people would be familiar with. 

### Active Users

- [x] 🔧 **4.** A beautiful definition of Active users, consider adding a sentence stating how we will calculate it - such as: "To get the daily active users, we need to count the number of unique `user_id`s for each `session_date`."

### Monthly active users

- [x] 🔧 **5.** Consider removing the `###` for enter date trunc etc.. as headers and sub headers should be for sections. 

- [x] 🔧 **6.** Consider separating the arrow from the function and the outputs like this:

- `DATE_TRUNC('week', '2018-06-12') :: DATE` → `'2018-06-11'`
- `DATE_TRUNC('month', '2018-06-12') :: DATE` → `'2018-06-01'`
- `DATE_TRUNC('quarter', '2018-06-12') :: DATE` → `'2018-04-01'`
- `DATE_TRUNC('year', '2018-06-12') :: DATE` → `'2018-01-01'`

### Registered Users

- [x] 🔧 **7.** Better to have a sub-sub section here that is just named "Getting registration dates" and another one named "Number of registrations per month". You can include the markdown on Common table Expressions there. 

### Growth and Window Functions

- [x] 🔧 **8.** Use bold instead of a sub-subsection for "Window Functions". 

#### Self Joins

- [x] 🔧  **9.** Consider adding an image like this one here: 
![image](https://user-images.githubusercontent.com/48436758/83518570-e4ff8c00-a4da-11ea-8a5a-25ea46df2bcc.png)

## Intangibles 

- [x] 🔧 **10.** This is technically simulated data, but make sure to connect it with real-life examples. For example, you can state that almost a lot of consumer-facing apps like Netflix, Amazon, etc.. utilize similar techniques when analyzing how their customers behave.

**Comment by michlsemn** [comment]
Noted, thanks a lot for the feedback -- all these points should be fixed from my end by tomorrow.

**Comment by adelnehme** [comment]
Hi @michlsemn :wave:

Hope you're well and apologies for the slight delay getting this review in time. I took a look at the solution notebook and it's looking really solid. I think the current content is a bit on the shorter side and could be beefed up with the following:

- [x] 🔧 **1.** Having another table named `users` that has `user_id`, `country_of_origin`, `age`  to be able to run a few high-level questions about what type of users facespace _(great name btw)_ has like average age and number of users per country at the beginning of the notebook. This section could be called "Data Exploration" and would include exploring both tables, calculating average age of users, and number of users per country. This could all be simulated data and you don't need to have 100+ countries (5-8 would be enough and you can even crack a joke that it's not a lot 😉). There is no need to do joins as well.

- [x] 🔧 **2.** Make sure to add Q&A sessions as a sub-header `##` after having completed the code in the following section:

> - Data Exploration mentioned in **1**
> - Registration dates
> - Growth and window functions
> - At the end of notebook

**Comment by adelnehme** [comment]
Hi @michlsemn :wave:

I took a look at the learner notebook and it's looking great! My only feedback:

- [x] 🔧 **1.** Making sure that learner notebook is updated after having implemented feedback on solution notebook above ^^

- [x] 🔧 **2.** Make sure to delete the output of queries in the learner notebook like in the picture below - you can do so on colabs and then save it back into GitHub (by either downloading the ipynb file and uploading it to GitHub **or** using `file` - `save a copy in GitHub`.
 
![image](https://user-images.githubusercontent.com/48436758/83854111-8888b080-a716-11ea-86cf-dca7dbfe4496.png)

**Comment by michlsemn** [comment]
Done for both -- I actually just pushed two new notebooks with everything cleared and some changes made, so I'm not sure which version you checked.

**Comment by adelnehme** [comment]
Hi @michlsemn :wave:

Thanks for the update! Maybe it would have been a cached version maybe? I now saw the updated notebooks and it's looking great. Since this a social media case study, definitely takes it to the next level if we add the country of origin example as well (in both notebooks from there). 


A part from that and the Q&A we're good to go! 😄

**Comment by michlsemn** [comment]
Done!

**Comment by adelnehme** [comment]
Hi @michlsemn :wave: All looking good! I can't seem to find the country of origin column in the data overview section though. Am I missing something?

**Comment by michlsemn** [comment]
I added gender instead yesterday -- is that fine or would you like me to change it to nationality?

**Comment by adelnehme** [comment]
@michlsemn Apologies for the inconsistency in my feedback from 2 days ago and now about gender and now nationality - but given this is a social media dataset/case study I think adding country of origin is an important data point here (arguably more important than gender). Thanks again for the flexibility and apologies for the inconsistency!

**Comment by michlsemn** [comment]
No problem -- will have this done in about an hour.

**Comment by adelnehme** [comment]
Thank you 🙏 @michlsemn

**Comment by michlsemn** [comment]
Done

**Comment by adelnehme** [comment]
Looks perfect! Mabrouk :)
